plugins = {
{  path = "FuckPSSE.suprx", name = "FuckPSSE by SilicaAndPina v1.1", section = "ALL", KEY = "INSTALLP_DESC_FUCKPSSE", version = "0001", desc = LANGUAGE["INSTALLP_DESC_FUCKPSSE"],},
{  path = "VGi.suprx", name = "VGi by Electry v0.7", section = "ALL", KEY = "INSTALLP_DESC_VGI", version = "0001", desc = LANGUAGE["INSTALLP_DESC_VGI"],},
{  path = "PSMPatch.suprx", name = "PSMPatch by SilicaAndPina v1.1", section = "ALL", KEY = "INSTALLP_DESC_PSMPATCH", version = "0001", desc = LANGUAGE["INSTALLP_DESC_PSMPATCH"],},
{  path = "trophax2.0.suprx", name = "TropHAX by SilicaAndPina v2.0", section = "ALL", KEY = "INSTALLP_DESC_TROPHAX", version = "0001", desc = LANGUAGE["INSTALLP_DESC_TROPHAX"],},
{  path = "reRescaler.suprx", section2 = "KERNEL", KEY = "INSTALLP_DESC_RESCALER", path2 = "ioplus.skprx", desc = LANGUAGE["INSTALLP_DESC_RESCALER"], version = "0001", section = "ALL", name = "reRescaler by Rinnegatamante v1.0",},
{  path = "Framecounter.suprx", name = "Framecounter by Rinnegatamante v1.2", section = "ALL", KEY = "INSTALLP_DESC_FRAMECOUNTER", version = "0001", desc = LANGUAGE["INSTALLP_DESC_FRAMECOUNTER"],},
{  path = "VitaGrafix.suprx", section2 = "KERNEL", KEY = "INSTALLP_DESC_VITAGRAFIX", path2 = "ioplus.skprx", desc = LANGUAGE["INSTALLP_DESC_VITAGRAFIX"], version = "0001", section = "ALL", name = "VitaGrafix by Electry v5.0.1",},
{  path = "oclockvita.suprx", name = "Oclock Vita by frangarcj v1.2.1", section = "ALL", KEY = "INSTALLP_DESC_OVERCLOCK", version = "0001", desc = LANGUAGE["INSTALLP_DESC_OVERCLOCK"],},
{  path = "vsh.suprx", section2 = "KERNEL", KEY = "INSTALLP_DESC_VSHMENU", path2 = "kuio.skprx", desc = LANGUAGE["INSTALLP_DESC_VSHMENU"], version = "0001", section = "ALL", name = "PSV-VSH MENU by joel16 v3.4",},
{  path = "InfiniteNet.suprx", name = "InfiniteNet by Rinnegatamante v1.0", section = "ALL", KEY = "INSTALLP_DESC_INFINITENET", version = "0001", desc = LANGUAGE["INSTALLP_DESC_INFINITENET"],},
{  path = "TurboPad.suprx", section2 = "KERNEL", KEY = "INSTALLP_DESC_TURBOPAD", path2 = "kuio.skprx", desc = LANGUAGE["INSTALLP_DESC_TURBOPAD"], version = "0001", section = "ALL", name = "TurboPad by Rinnegatamante v0.3",},
{  path = "forcelang.suprx", section2 = "KERNEL", KEY = "INSTALLP_DESC_FORCELANG", path2 = "ioplus.skprx", desc = LANGUAGE["INSTALLP_DESC_FORCELANG"], version = "0001", section = "ALL", name = "forcelang by xdanieldzd v0.2U",},
{  path = "remaPSV.suprx", section2 = "KERNEL", KEY = "INSTALLP_DESC_REMAPSV", path2 = "ioplus.skprx", desc = LANGUAGE["INSTALLP_DESC_REMAPSV"], version = "0001", section = "ALL", name = "remaPSV by Rinnegatamante v1.1",},
{  path = "FreePSM.suprx", name = "FreePSM by SilicaAndPina v1.1", section = "ALL", KEY = "INSTALLP_DESC_FREEPSM", version = "0001", desc = LANGUAGE["INSTALLP_DESC_FREEPSM"],},
{  path = "ShowInfoLite.suprx", name = "ShowInfo Lite by Yoti v0.2", section = "ALL", KEY = "INSTALLP_DESC_SHOWINFO", version = "0001", desc = LANGUAGE["INSTALLP_DESC_SHOWINFO"],},
{  path = "ShowInfo.suprx", name = "ShowInfo Full by Yoti v0.6", section = "ALL", KEY = "INSTALLP_DESC_SHOWINFOFU", version = "0001", desc = LANGUAGE["INSTALLP_DESC_SHOWINFO"],},
{  path = "WDNF.suprx", name = "WDNF by EchoDev & Rinnegatamante v1.0", section = "ALL", KEY = "INSTALLP_DESC_WDNF", version = "0001", desc = LANGUAGE["INSTALLP_DESC_WDNF"],},
{  path = "WDNR.suprx", name = "WDNR by Rinnegatamante v1.0", section = "ALL", KEY = "INSTALLP_DESC_WDNR", version = "0001", desc = LANGUAGE["INSTALLP_DESC_WDNR"],},
{  path = "MakePsmGreatAgain.suprx", name = "MakePsmGreatAgain by SilicaAndPina v1.4", section = "ALL", KEY = "INSTALLP_DESC_MAKEPSM", version = "0001", desc = LANGUAGE["INSTALLP_DESC_MAKEPSM"],},
{  path = "derinclocks.skprx", name = "DerInClocKS by teakhanirons v1.0", section = "KERNEL", KEY = "INSTALLP_DESC_DERIN", version = "0001", desc = LANGUAGE["INSTALLP_DESC_DERIN"],},
{  path = "NoPowerLimits.skprx", name = "NoPowerLimits by Electry v1.1", section = "KERNEL", KEY = "INSTALLP_DESC_NOPOWERL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_NOPOWERL"],},
{  path = "lolita500.skprx", name = "lolita500 by teakhanirons v1.0", section = "KERNEL", KEY = "INSTALLP_DESC_LOLITA", version = "0001", desc = LANGUAGE["INSTALLP_DESC_LOLITA"],},
{  path = "videoDebug.skprx", name = "VideoDebug by SilicaAndPina v1.0", section = "KERNEL", KEY = "INSTALLP_DESC_VIDEODBG", version = "0001", desc = LANGUAGE["INSTALLP_DESC_VIDEODBG"],},
{  path = "lolita444.skprx", name = "lolita444 by teakhanirons v0.5", section = "KERNEL", KEY = "INSTALLP_DESC_LOLITA4", version = "0001", desc = LANGUAGE["INSTALLP_DESC_LOLITA"],},
{  path = "nonpdrm.skprx", name = "NoNpDrm by TheOfficialFloW v1.3", section = "KERNEL", KEY = "INSTALLP_DESC_NONPDRM", version = "0002", desc = LANGUAGE["INSTALLP_DESC_NONPDRM"],},
{  path = "monaural.skprx", name = "Monaural by cuevavirus v1.0.0", section = "KERNEL", KEY = "INSTALLP_DESC_MONAURAL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_MONAURAL"],},
{  path = "PSVshell.skprx", name = "PSVshell by Electry v1.1", section = "KERNEL", KEY = "INSTALLP_DESC_PSVSHELL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_PSVSHELL"],},
{  path = "bicr.skprx", name = "PSP2-batteryFixer by SKGleba v1.1", section = "KERNEL", KEY = "INSTALLP_DESC_BATFIX", version = "0001", desc = LANGUAGE["INSTALLP_DESC_BATFIX"],},
{  path = "custom_boot_splash.skprx", name = "Custom Boot Splash by Princess of Sleeping", section = "KERNEL", KEY = "INSTALLP_DESC_CUSTOMBOOTSPLASH", version = "0001", desc = LANGUAGE["INSTALLP_DESC_CUSTOMBOOTSPLASH"],},
{  path = "nosleep.skprx", name = "nosleep by NamelessGhoul0 v1.1", section = "KERNEL", KEY = "INSTALLP_DESC_NOSLEEP", version = "0001", desc = LANGUAGE["INSTALLP_DESC_NOSLEEP"],},
{  path = "0syscall6.skprx", name = "0syscall6 by SKGleba v1.2", section = "KERNEL", KEY = "INSTALLP_DESC_SYSCALL6", version = "0001", desc = LANGUAGE["INSTALLP_DESC_SYSCALL6"],},
{  path = "reF00D.skprx", name = "reF00D by FAPS Team v1.0", section = "KERNEL", KEY = "INSTALLP_DESC_REFOOD", config = "keys.bin", version = "0001", desc = LANGUAGE["INSTALLP_DESC_REFOOD"],},
{  path = "adrenaline_kernel.skprx", name = "Adrenaline by TheOfficialFloW (Fix double touch)", section = "KERNEL", KEY = "INSTALLP_DESC_ADRENALINE", version = "0001", desc = LANGUAGE["INSTALLP_DESC_ADRENALINE"],},
{  path = "viimote.skprx", name = "viimote by xerpi v1.2", section = "KERNEL", KEY = "INSTALLP_DESC_VIIMOTE", version = "0001", desc = LANGUAGE["INSTALLP_DESC_VIIMOTE"],},
{  path = "vitastick.skprx", name = "vitastick by xerpi v0.4.1 alpha", section = "KERNEL", KEY = "INSTALLP_DESC_VITASTICK", version = "0001", desc = LANGUAGE["INSTALLP_DESC_VITASTICK"],},
{  path = "udcd_uvc_lcd_off.skprx", name = "udcd_uvc LCD by xerpi v1.4", section = "KERNEL", KEY = "INSTALLP_DESC_UDCDUVCL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_UDCDUVCL"],},
{  path = "dsmotion.skprx", section2 = "ALL", KEY = "INSTALLP_DESC_DSMOTION", path2 = "dsmotion.suprx", desc = LANGUAGE["INSTALLP_DESC_DSMOTION"], version = "0001", section = "KERNEL", name = "DSMotion by OperationNT414C v1.2",},
{  path = "AnalogsEnhancer.skprx", KEY = "INSTALLP_DESC_ANALOGSENHANCER", desc = LANGUAGE["INSTALLP_DESC_ANALOGSENHANCER"], configpath = "ur0:tai/", config = "AnaEnCfg.txt", version = "0001", section = "KERNEL", name = "AnalogsEnhancer by Rinnegatamante v1.1",},
{  path = "usbmc.skprx", name = "usbmc by yifanlu v6 (only for PSTV)", section = "KERNEL", KEY = "INSTALLP_DESC_USBMC", version = "0001", desc = LANGUAGE["INSTALLP_DESC_USBMC"],},
{  path = "ioplus.skprx", name = "ioplus by dots-tb v0.1", section = "KERNEL", KEY = "INSTALLP_DESC_IOPLUS", version = "0001", desc = LANGUAGE["INSTALLP_DESC_IOPLUS"],},
{  path = "vitacheat.skprx", name = "Vitacheat Z05 BETA by r0ah FOR 3.65+", section = "KERNEL", KEY = "INSTALLP_DESC_VITACHEAT", version = "0001", desc = LANGUAGE["INSTALLP_DESC_VITACHEAT"],},
{  path = "udcd_uvc_oled_off.skprx", name = "udcd_uvc OLED by xerpi v1.4", section = "KERNEL", KEY = "INSTALLP_DESC_UDCDUVCO", version = "0001", desc = LANGUAGE["INSTALLP_DESC_UDCDUVCO"],},
{  path = "ds4vita.skprx", name = "ds4vita by xerpi v1.2", section = "KERNEL", KEY = "INSTALLP_DESC_DS4VITA", version = "0001", desc = LANGUAGE["INSTALLP_DESC_DS4VITA"],},
{  path = "noavls.skprx", name = "NoAVLS by SilicaAndPina", section = "KERNEL", KEY = "INSTALLP_DESC_NOAVLS", version = "0001", desc = LANGUAGE["INSTALLP_DESC_NOAVLS"],},
{  path = "vitabright.skprx", name = "Vitabright by devnoname120 v1.0", section = "KERNEL", KEY = "INSTALLP_DESC_VITABRIGHT", config = "vitabright_lut.txt", version = "0001", desc = LANGUAGE["INSTALLP_DESC_VITABRIGHT"],},
{  path = "nonpdrm_un.skprx", name = "NoNpDrm Unofficial by LMAN v1.4", section = "KERNEL", KEY = "INSTALLP_DESC_NONPDRMU", version = "0001", desc = LANGUAGE["INSTALLP_DESC_NONPDRM"],},
{  path = "udcd_uvc.skprx", name = "udcd_uvc by xerpi v1.4", section = "KERNEL", KEY = "INSTALLP_DESC_UDCDUVC", version = "0001", desc = LANGUAGE["INSTALLP_DESC_UDCDUVC"],},
{  path = "repatch.skprx", name = "Repatch by dots-tb v3.0", section = "KERNEL", KEY = "INSTALLP_DESC_REPATCH", version = "0001", desc = LANGUAGE["INSTALLP_DESC_REPATCH"],},
{  path = "lolicon.skprx", name = "LOLIcon by dots-tb v1.0.1.1 HOTFIX A", section = "KERNEL", KEY = "INSTALLP_DESC_LOLICON", version = "0001", desc = LANGUAGE["INSTALLP_DESC_LOLICON"],},
{  path = "repatch_4.skprx", name = "Repatch by dots-tb v2.71", section = "KERNEL", KEY = "INSTALLP_DESC_REPATCH271", version = "0001", desc = LANGUAGE["INSTALLP_DESC_REPATCH"],},
{  path = "ds3vita.skprx", name = "ds3vita by xerpi Beta3", section = "KERNEL", KEY = "INSTALLP_DESC_DS3VITA", version = "0001", desc = LANGUAGE["INSTALLP_DESC_DS3VITA"],},
{  path = "noled.skprx", name = "noled by reprep v1.1", section = "KERNEL", KEY = "INSTALLP_DESC_NOLED", version = "0001", desc = LANGUAGE["INSTALLP_DESC_NOLED"],},
{  path = "nopsmdrm.skprx", name = "NoPsmDrm by frangarcj v1.4", section = "KERNEL", KEY = "INSTALLP_DESC_NOPSMDRM", version = "0001", desc = LANGUAGE["INSTALLP_DESC_NOPSMDRM"],},
{  path = "vitacheat360.skprx", name = "Vitacheat Z05 BETA FOR 3.60", section = "KERNEL", KEY = "INSTALLP_DESC_VITACHEAT2", version = "0001", desc = LANGUAGE["INSTALLP_DESC_VITACHEAT"],},
{  path = "AnalogStickDisable_LeftToRight.skprx", name = "AnalogStickDisable Left To Right by Yoti v1.2", section = "KERNEL", KEY = "INSTALLP_DESC_ANALOGSTICK1", version = "0001", desc = LANGUAGE["INSTALLP_DESC_ANALOGSTICK1"],},
{  path = "AnalogStickDisable.skprx", name = "AnalogStickDisable by Hack-Usagi v1.2", section = "KERNEL", KEY = "INSTALLP_DESC_ANALOGSTICK", version = "0001", desc = LANGUAGE["INSTALLP_DESC_ANALOGSTICK"],},
{  path = "AnalogStickDisable_SwapLeftAndRight.skprx", name = "AnalogStickDisable Swap Left To Right by Yoti v1.2", section = "KERNEL", KEY = "INSTALLP_DESC_ANALOGSTICK3", version = "0001", desc = LANGUAGE["INSTALLP_DESC_ANALOGSTICK"],},
{  path = "AnalogStickDisable_RightToLeft.skprx", name = "AnalogStickDisable Right To Left by Yoti v1.2", section = "KERNEL", KEY = "INSTALLP_DESC_ANALOGSTICK2", version = "0001", desc = LANGUAGE["INSTALLP_DESC_ANALOGSTICK"],},
{  path = "cidSpoof.skprx", name = "cidSpoofer by SilicaAndPina v1.0", section = "KERNEL", KEY = "INSTALLP_DESC_CIDSPOOF", version = "0001", desc = LANGUAGE["INSTALLP_DESC_CIDSPOOF"],},
{  path = "AnalogStickDisable_LeftOnly.skprx", name = "AnalogStickDisable Left Only by Hack-Usagi v1.1", section = "KERNEL", KEY = "INSTALLP_DESC_ANALOGSTICK4", version = "0001", desc = LANGUAGE["INSTALLP_DESC_ANALOGSTICK"],},
{  path = "AnalogStickDisable_RightOnly.skprx", name = "AnalogStickDisable Right Only by Hack-Usagi v1.1", section = "KERNEL", KEY = "INSTALLP_DESC_ANALOGSTICK5", version = "0001", desc = LANGUAGE["INSTALLP_DESC_ANALOGSTICK"],},
{  path = "vitacompanion.suprx", name = "Vitacompanion by devnoname120 v1.00", section = "main", KEY = "INSTALLP_DESC_VITACOMPA", version = "0001", desc = LANGUAGE["INSTALLP_DESC_VITACOMPA"],},
{  path = "download_enabler.suprx", name = "Download Enabler v5 by TheOfficialFloW (VitaTweaks)", section = "main", KEY = "INSTALLP_DESC_DENABLER", version = "0001", desc = LANGUAGE["INSTALLP_DESC_DENABLER"],},
{  path = "nolockscreen.suprx", name = "NoLockScreen v2 by TheOfficialFloW (VitaTweaks)", section = "main", KEY = "INSTALLP_DESC_NOLOCKSCREEN", version = "0001", desc = LANGUAGE["INSTALLP_DESC_NOLOCKSCREEN"],},
{  path = "jav.suprx", name = "volume_profile by cuevavirus v1.1.1", section = "main", KEY = "INSTALLP_DESC_VOLUPROF", version = "0001", desc = LANGUAGE["INSTALLP_DESC_VOLUPROF"],},
{  path = "custom_warning.suprx", name = "Custom Warning v2 by TheOfficialFloW (VitaTweaks)", section = "main", KEY = "INSTALLP_DESC_CUSTOMWARNING", config = "custom_warning.txt", version = "0001", desc = LANGUAGE["INSTALLP_DESC_CUSTOMWARNING"],},
{  path = "notrophymsg.suprx", name = "NoTrophyMsg by TheOfficialFloW (VitaTweaks)", section = "main", KEY = "INSTALLP_DESC_NOTROPHYMSG", version = "0001", desc = LANGUAGE["INSTALLP_DESC_NOTROPHYMSG"],},
{  path = "reSkype.suprx", name = "reSkype by SilicaAndPina v1.0", section = "main", KEY = "INSTALLP_DESC_RESKYPE", version = "0001", desc = LANGUAGE["INSTALLP_DESC_RESKYPE"],},
{  path = "AutoBoot.suprx", name = "Autoboot by Rinnegatamante v1.2 (only for 3.60/3.65)", section = "main", KEY = "INSTALLP_DESC_AUTOBOOT", version = "0001", desc = LANGUAGE["INSTALLP_DESC_AUTOBOOT"],},
{  path = "pngshot.suprx", name = "pngshot by xyzz v1.3", section = "main", KEY = "INSTALLP_DESC_PNGSHOT", version = "0001", desc = LANGUAGE["INSTALLP_DESC_PNGSHOT"],},
{  path = "vflux.suprx", name = "Vflux by Applelo v0.5", section = "main", KEY = "INSTALLP_DESC_VFLUX", version = "0001", desc = LANGUAGE["INSTALLP_DESC_VFLUX"],},
{  path = "shellbat_mod.suprx", name = "Shellbat Mod by devnoname120 vr10", section = "main", KEY = "INSTALLP_DESC_SHELLBATM", version = "0001", desc = LANGUAGE["INSTALLP_DESC_SHELLBATM"],},
{  path = "shellsecbat.suprx", name = "Shellsecbat by OperationNT414C v10", section = "main", KEY = "INSTALLP_DESC_SHELLSECBAT", version = "0001", desc = LANGUAGE["INSTALLP_DESC_SHELLSECBAT"],},
{  path = "shellbat.suprx", name = "Shellbat by nowrep vr10", section = "main", KEY = "INSTALLP_DESC_SHELLBAT", version = "0001", desc = LANGUAGE["INSTALLP_DESC_SHELLBAT"],},
{  path = "DolcePolce.suprx", name = "DolcePolce by SilicaAndPina v1.0", section = "main", KEY = "INSTALLP_DESC_DOLCEPOLCE", version = "0001", desc = LANGUAGE["INSTALLP_DESC_DOLCEPOLCE"],},
{  path = "ps4linkcontrols.suprx", name = "vita-ps4linkcontrols r7 by nowrep", section = "NPXS10013", KEY = "INSTALLP_DESC_PS4LINK", version = "0001", desc = LANGUAGE["INSTALLP_DESC_PS4LINK"],},
{  path = "macspoofer.suprx", section2 = "NPXS10016", KEY = "INSTALLP_DESC_MACSPOOF", path2 = "macspoofer.suprx", desc = LANGUAGE["INSTALLP_DESC_MACSPOOF"], version = "0001", section = "NPXS10015", name = "vita-macspoofer by Freakler",},
{  path = "reScreeny.suprx", name = "reScreeny by dots_tb v1.0", section = "NPXS10036", KEY = "INSTALLP_DESC_RESCREENY", version = "0001", desc = LANGUAGE["INSTALLP_DESC_RESCREENY"],},
}
