-- Constants

--APP_REPO = "theheroGAC"
--APP_PROJECT = "AutopluginII"
--APP_FOLDER = "AUTOPLUG2"
APP_REPO = "ONElua"
APP_PROJECT = "APII"--APII.vpk
APP_FOLDER = "APIITEST0"

APP_VERSION_MAJOR = 0x00 -- major.minor
APP_VERSION_MINOR = 0x06
APP_VERSION = ((APP_VERSION_MAJOR << 0x18) | (APP_VERSION_MINOR << 0x10)) -- Union Binary
